name: CI/PR
on:
  pull_request:
  push:
    branches:
      - master
      - validate/*

jobs:
  check_diff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: yarn
      run: yarn

    - name: "yarn run build"
      run: yarn run build

    # - name: "yarn run test"
    #   run: yarn run test

    - name: "check for uncommitted changes"
      # Ensure no changes, but ignore node_modules dir since dev/fresh ci deps installed.
      run: |
        git diff --exit-code --stat -- . ':!node_modules' \
        || (echo "##[error] found changed files after build. please 'yarn run build'" \
                 "and check in all changes" \
            && exit 1)
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: nbgv -c -p src
      uses: ./
      with:
        path: src
        allVars: false
    - name: Print env vars
      run: gci env:NBGV_*,env:Git*
      shell: pwsh
    - name: nbgv -a -p src
      uses: ./
      with:
        path: src
        commonVars: false
    - name: Print env vars
      run: gci env:NBGV_*,env:Git*
      shell: pwsh
